### ISSUE TITLE
Prototype

### ISSUE THREAD

**Issue by pastrana98** [Arquisoft/dechat_en2a#11]
Hi,
I've created a Prototype of the App it is very basic but we can use it as a base to build on it.

## How it works

* First, you have to log in with your account.
* Create a file (it creates a chat01.txt in your repo).
* Click on Read to see the content of that file.
* Change the text of the text area.
* Update the changes.

**Comment by flecktarn121** [comment]
I will try to add an interface more similar to a chat. Do I create a new branch, or work on yours directly?

**Comment by EnriqueJRodriguez** [comment]
Use a new branch so enayone can try to add other interfaces.
