### ISSUE TITLE
User Load Test

### ISSUE THREAD

**Issue by tgperry** [Arquisoft/dechat_en2a#113]
At least some form of load test, likely through Gatling, should be implemented with our project as per Labra's recommendation.

**Comment by pastrana98** [comment]
I am researching about it, I'll try to have it for today.

**Comment by pastrana98** [comment]
I'm having a problem while trying to record it because in localhost using the proxy I cannot login.

**Comment by AlvasanG** [comment]
As I dont know if you have succesfully found a workaround I will jump into this aswell.

**Comment by pastrana98** [comment]
A test without login in is done.

**Comment by AlvasanG** [comment]
If you could provide of 4+ graphs of the tests done, with different loads (not bigger than 50) I can work on extrapolating data as referenced on #115.

Else if you tell me the parameters of the test I can replicate it later.

**Comment by pastrana98** [comment]
The link to the results is here (also in the wiki/resources): https://drive.google.com/drive/folders/1UMO8MCWvwPod7Wz6JnGJ9DZhbUmJh-wi
