### ISSUE TITLE
Find XML Schema for our data model

### ISSUE THREAD

**Issue by josecurioso** [Arquisoft/dechat_en2a#15]
In order to use RDF we should find an XML Schema that fits our needs for a char application storage.

**Comment by flecktarn121** [comment]
As I suspected, there is a [W3C specification](https://www.w3.org/TR/xmsg/) for chat messages in XML. The XML schema is [this](https://www.w3.org/TR/xmsg/message.xsd) .
PS: remember to click on _view source_ in order to see the schema itself, otherwise you would see the parsed schema.
