### ISSUE TITLE
Documentation enhancements from the first review

### ISSUE THREAD

**Issue by josecurioso** [Arquisoft/dechat_en2a#17]
These are the points that should be addressed as stated in the first review, remember to assign yourself and mark when done:
- [x] Context and Scope: make less technical diagrams.
- [x] Solution Strategy: reduce the amount of raw text (package in lists and tables).
* General:
  - [x] Add legends to the diagrams
  - [x] Take care of the symbols used
  - [x] Delete contents of not-yet-done pages and replace with TO-DO

**Comment by YerayG** [comment]
Most of the problems addressed during the first review session regarding the Context and Scope diagrams are fixed. The section overall is also improved. However, they are still subject to change if further issues are encountered as the project evolves.

**Comment by tgperry** [comment]
The Solution Strategy has been updated for concision and the information regarding tools we plan on using that was originally in Solution Strategy has been moved to Design Decisions as per Labra's recommendation.
