### ISSUE TITLE
Interaction between Pods

### ISSUE THREAD

**Issue by pastrana98** [Arquisoft/dechat_en2a#18]
After asking on the solid forum, they answer me with some links that might be useful.
[Link to the question](https://forum.solidproject.org/t/giving-permissions-to-a-friend/1350/2)

This is a new feature of the proyect, the main goal of it, is to be able to give permission to someone and  interact in his Pod.
It would be great to start a prototype and see if we can do it programmatically.

**Comment by pastrana98** [comment]
I've been doing research about this and I think I've found one way to do it. I haven´t been able to prove it but it would be as simple has changing the permissions of the file .acl of each file.

**Comment by pastrana98** [comment]
This would be the code added to the acl file (using RDF) in order to give permisions to Alice to Read and Write
 ```
<rdf:Description rdf:about="#ReadWrite">
        <rdf:type rdf:resource="http://www.w3.org/ns/auth/acl#Authorization"/>
        <n0:accessTo rdf:resource="chat01.txt"/>
        <n0:agent rdf:resource="https://alice.inrupt.net/profile/card#me"/>
        <n0:mode rdf:resource="http://www.w3.org/ns/auth/acl#Read"/>
        <n0:mode rdf:resource="http://www.w3.org/ns/auth/acl#Write"/>
    </rdf:Description>
```

**Comment by josecurioso** [comment]
This issue is continued in #29 and therefore closed
