### ISSUE TITLE
Sligth change on the telegram idea

### ISSUE THREAD

**Issue by flecktarn121** [Arquisoft/dechat_en2a#2]
After some careful investigation, I have reached 2 conclusions:

1. Either the Telegram team or me do not know the exact meaning of client is. [TDLib](https://core.telegram.org/tdlib) is some sort of middle layer between applications and the Telegram infrastructure (and therefore not suitable for our purposes).
2. The [web client](https://github.com/zhukov/webogram) (the application frontend, now for real) is also available as free software under GPL, so we can still carry on with the idea. Plus, it runs on JavaScript using Angular.

Feel free to give any feedback.

PS: first issue on this page ever, not sure if I am using it properly.

**Comment by josecurioso** [comment]
Our only option if we choose to pursue this further is to use the web client code. Personally I think it will turn out to be a pain to understand and adapt though. We can discuss this further the 11th

**Comment by josecurioso** [comment]
We agreed to drop the idea in Monday's meeting. Issue closed.
