### ISSUE TITLE
Usage of Turtle

### ISSUE THREAD

**Issue by AlvasanG** [Arquisoft/dechat_en2a#20]
In order to store the data of the messages within a users pod we will use turtle rdf format. 

The basics of the format are specified on its w3c standard webpage [Turtle](https://www.w3.org/TR/turtle/).
In order to use turtle rdf within our project we should be using rdflib.js [https://github.com/solid/solid-tutorial-rdflib.js](https://github.com/solid/solid-tutorial-rdflib.js), which contains simple tutorials about the usage of the library.

What we need to do is store:
- Sender's pod's uri.
- Message.
- Reciever's pod's uri.

Every message shall be parsed as a tuple with the aforementioned schema.

**Comment by AlvasanG** [comment]
Here are some tutorials / examples that might be useful in understanding how turtle is defined and how rdflib works:

Turtle tutorial -> [https://www.youtube.com/watch?v=AXN9gszoti4](url)
Rdflib.js examples -> [https://github.com/linkeddata/rdflib.js/issues/43](url)

**Comment by AlvasanG** [comment]
Also the way of managing files is done with SolidFileClient but I forgot to place the reference link in the other messages. Here it is [https://www.npmjs.com/package/solid-file-client](url)

**Comment by AlvasanG** [comment]
As of now we are able to store the information into a the graph localy and then push it into the file in the users POD. It has some major drawbacks thay I will specify later:

- The information is stored localy but appears to be wrongly stored, must dig into the add method and other possible alternatives (better use of parameters) in order to store the data correctly.
- The information is not stored correctly hence no tuples are being created in the ttl file but rather just the "reciever" of the text.

After this 2 major issues are fixed, or at least 1 of those, I will update again this issue and commit the changes into the branch.

Useful links:

- Examples of the basic funtionalities when working with files -> [https://forum.solidproject.org/t/rdflib-documentation/585/4](url)
- Specifying data types with XSD -> [https://forum.solidproject.org/t/specify-data-types-with-rdflib-js/1156](url)
      - The specific types are avaliable here -> [https://docs.oracle.com/cd/E14154_01/dev.835/e12868/e01_soap_types.htm](url)
- How to read the content from a file stored in a POD -> [https://forum.solidproject.org/t/how-to-read-data-from-rdf-file-from-solid-pod/1332](url)
      - Further investigation will be needed in order to correctly show the information from the file and the parsing we make of the file.

**Comment by AlvasanG** [comment]
As I am unable to correctly create a tuple everytime a message is sent, and rather it just adds the information into the already existing tuple I have created a [discussion](https://forum.solidproject.org/t/creating-a-new-tuple-with-rdflib/1386) in the solid forum.

Will try to work further on my own while I wait for some feedback on the solid forum.

**Comment by AlvasanG** [comment]
As indicated on the solid forum, the usage of a ontology or vocabulary to represent the messages is needed. After some digging I found [this](https://developer.gnome.org/ontology/stable/nmo-ontology.html) ontology, whose SMS section fits our needs greately.

I will need to change how the message is being sent to adapt to this new ontology in the following days,  [here](http://oscaf.sourceforge.net/nmo.html) is the documentation of the aforementioned ontology.

**Comment by josecurioso** [comment]
Based on the information compiled in this issue, a bunch of helper methods for reading and writing messages to the POD's native chat format have been implemented on [joseDev]() branch but as stated in [#19](https://github.com/Arquisoft/dechat_en2a/issues/19#issuecomment-471126317) it is no ready for a pull request yet.

**Comment by AlvasanG** [comment]
As we already have a base using ttl I will proceed to close this issue. If further assistance is needed with ttl we can open new issues regarding those specific problems.
