### ISSUE TITLE
Numeration of the documentation

### ISSUE THREAD

**Issue by EnriqueJRodriguez** [Arquisoft/dechat_en2a#25]
We should add the corresponding numbers to enhance the presentation of the documentation.

**Comment by josecurioso** [comment]
You mean to the table of contents and the titles? I agree, it would help navigating the page. Let's wait and see what the others think and you can add it easily.

**Comment by josecurioso** [comment]
Nobody has complained about the proposition so feel free to add the numbers and close the issue.
