### ISSUE TITLE
Service testing

### ISSUE THREAD

**Issue by flecktarn121** [Arquisoft/dechat_en2a#28]
At the current time, we have done no unit testing whatsoever. 
Angular provides its own tool for unit testing, [jasmine](https://angular.io/guide/testing#testing). Considering its complete integration for the system, it is probably our best option.
Considering the difficulty of testing the components (view) we will just test the services, and leave the view for the next deliverable.

**Comment by josecurioso** [comment]
Appart from testing we should also reconfigure the coverage CI tool so it reports the percentage accurately.

**Comment by josecurioso** [comment]
After the last merge both tests and coverage are working correctly.
