### ISSUE TITLE
Granting permissions per folder structure

### ISSUE THREAD

**Issue by josecurioso** [Arquisoft/dechat_en2a#29]
We need to grant read and write permissions for the chat structure to the other person/people in the chat room. As discussed in class it will be done using rdflib and the acl file and syntax that is already standard.

**Comment by josecurioso** [comment]
This issue is a follow up from #18 which contains an example of the syntax, leaving it here for future reference.

**Comment by pastrana98** [comment]
I already know how to set permissions to a file, change them to a folder shouldn´t be a problem such it follows the same schema. I´ll try it as soon as posible.
