### ISSUE TITLE
App for learning Js

### ISSUE THREAD

**Issue by EnriqueJRodriguez** [Arquisoft/dechat_en2a#3]
If you like to learn in an interactive way or you want to refresh your knowledge of JavaScript there is an app available on the play store (I don't know if it is available on the app store) called "Aprende JavaScript"; I think it is quite useful and it can be used in english and spanish.

There you have a link to the app to have a look on your web breowser:
https://play.google.com/store/apps/details?id=com.sololearn.javascript

Also you have another intereting app to have your git account on your mobile phone:

https://play.google.com/store/apps/details?id=com.thirtydegreesray.openhub

**Comment by flecktarn121** [comment]
That is great Like, thank you very much. I will give it a try.
By the way, I have also found a [page](http://di002.edv.uniovi.es/~cueva/JavaScript/CursoJavaScript.html) with lots of JavaScript resources available. You should check it out.

**Comment by josecurioso** [comment]
Contents moved to their own wiki page.
