### ISSUE TITLE
Js IDEs

### ISSUE THREAD

**Issue by EnriqueJRodriguez** [Arquisoft/dechat_en2a#4]
If you are looking for a Js IDE my recommendations are:

Visual Studio Code:
Very nice look and feel and quite good multipurpose IDE
Download link:
https://code.visualstudio.com/download

Eclipse for JavaScript:
It is another version of Eclipse just for web development and also allows to code in Js, I did not test it but as it is on the Eclipse foundation web page we can assume that is good enough.
Download link:
https://www.eclipse.org/downloads/packages/release/2018-12/r/eclipse-ide-javascript-and-web-developers

If you know any better tool, please submit here the download link and explain briefly its advantages.

**Comment by josecurioso** [comment]
For further additions this topic is moving to the [wiki](https://github.com/Arquisoft/dechat_en2a/wiki/Resources)
