### ISSUE TITLE
app.component css

### ISSUE THREAD

**Issue by EnriqueJRodriguez** [Arquisoft/dechat_en2a#49]
I was modiffiying the css files and I came uppon a file wich is empty. Tell me if it is needed or not just to remove the file in that case.

**Comment by josecurioso** [comment]
We should keep the css files even if they are empty because they are referenced in the .ts file from the same component.

**Comment by EnriqueJRodriguez** [comment]
Same problem with loging-popup

**Comment by EnriqueJRodriguez** [comment]
Also friends-list .

**Comment by josecurioso** [comment]
This issue was discussed in class and can be closed
