### ISSUE TITLE
Logo for the application

### ISSUE THREAD

**Issue by EnriqueJRodriguez** [Arquisoft/dechat_en2a#52]
We need a logo

**Comment by Yasujizr** [comment]
Hi,

I design logo for open source projects. If your interest, u give me a brief information. What u want on logo; color, style, similiar logo example.

Cheers.

**Comment by josecurioso** [comment]
Thank you very much for the offer but this project is a class assignment and we don't know how our professor would feel about accepting such an important contribution from a person outside of the group/course. 
Anyways I will contact him ASAP and get back to you with whatever he tells me.
Again the offer is really appreciated.

**Comment by tgperry** [comment]
A logo has been created.
