### ISSUE TITLE
[DOC] Crosscutting Concepts

### ISSUE THREAD

**Issue by josecurioso** [Arquisoft/dechat_en2a#61]
Some formatting errors found on the page with "===", probably an easy fix. Also there is indeed session handling (in the form of the login information stored in local storage), persistence is primary (probably the most important part of the project) and now that the testing frameworks are configured you can add that information to the "Testing" section as well as finishing the "Building" one.

**Comment by flecktarn121** [comment]
Now the chapter reflect the state of the system
