### ISSUE TITLE
[DOC] Architecture Decisions

### ISSUE THREAD

**Issue by josecurioso** [Arquisoft/dechat_en2a#62]
After discussing it today the table in this page probably would fit better in a section about "technologies used" so we should update some info and delete other to make it better fit the theme.

**Comment by tgperry** [comment]
I've added some tools, but I'm not sure what you mean by the table would fit better in a section about technologies used. The table is labeled "Development Tools" which I figured was the same thing. Let me know how I can further improve it.

**Comment by flecktarn121** [comment]
Remember to add the decision about using the unit tests to generate the coverage.
