### ISSUE TITLE
[DOC] Quality Requirements

### ISSUE THREAD

**Issue by josecurioso** [Arquisoft/dechat_en2a#63]
We went over the quality requirements in class and we concluded that our application meets all of them except for the "Availability" part. We should discuss further in the group chat if the best course of action is to drop that branch or acknowledge that we won't be able to implement it in the time we have left without breaking a lot of things.

**Comment by tgperry** [comment]
We will leave this branch for the 3rd review tomorrow and determine if it should be dropped for the final product. The attributes that fall under availability could be very useful for the final product and may be easier to implement than we initially believe.

**Comment by tgperry** [comment]
Sorry I did not mean to close this yet. We will close if we determine we do not want to try and implement those elements of the quality requirements.
