### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by josecurioso** [Arquisoft/dechat_en2a#7]
Write the following parts of the documentation: 
- [x] Introduction
- [x] Architecture constraints
- [x] System Scope and Context
- [x] Solution Strategy
- [x] Glossary

**Comment by flecktarn121** [comment]
I will take care of the glossary part.
At first I will try to include some basic concepts that we will be using.
Should you happen to come across any term that you think needs to be included, please, let me know as soon as you can.

**Comment by AlvasanG** [comment]
I will mainly focus on the overall introduction of the project we will be developing on this curse, and begin doing a brief explanation about the overall rrequirements that could possible be expanded in future updates or parts that are yet to come.

**Comment by tgperry** [comment]
I will fill out the Solution Strategy section, focusing on our plan for reaching a final product for the assignment. Our choices and reasoning for specific development tools will be included. As we continue development and learn more about specific steps and actions we must take, this section will become more elaborative.

**Comment by YerayG** [comment]
I will be in charge of writing part of the System Scope and Context section. I will try to create diagrams or tables that represent the business context of the system we are going to be developing and a general view of the system and its stakeholders.
